name: Build rules dat files
on:
  workflow_dispatch:
  schedule:
    - cron: "30 22 * * *" # 6:30 AM UTC+8
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          echo "GOAMD64=v3" >> $GITHUB_ENV
          echo "BUILDTIME=$(TZ=Asia/Shanghai date +'%Y-%m-%d %H:%M')" >> $GITHUB_ENV
        shell: bash

      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout Energetic3906/domain-list-community
        uses: actions/checkout@v4
        with:
          repository: Energetic3906/domain-list-community
          ref: master
          path: community

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache-dependency-path: ./custom/go.sum

      - name: Build geosite-lite.dat file
        env:
          NO_SKIP: true
        run: |
          cd community || exit 1
          mkdir -p data
          curl -sSL https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/refs/heads/master/accelerated-domains.china.conf | grep "server=" | grep -v "#" | sed 's/ *server=\/\([^\/]*\)\/.*/\1/g' > ./data/cn
          go run ./ --datapath=./data --outputname geosite.dat
          mv geosite.dat ../
          cd ../
          echo "Current directory: $(pwd)"
          ls -l geosite.dat
          

      - name: Commit and push dat
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "101653181+github-actions[bot]@users.noreply.github.com"
          echo "Current directory: $(pwd)"
          git add geosite.dat
          commit_message="Update geosite.dat on $(date +'%Y-%m-%d')"
          git commit -m "$commit_message" || true
          git push -f -u origin main