name: Update Ruleset

on:
  schedule:
    - cron: '0 6 * * *' # 每天早上6点执行
  push:
    branches:
      - main

jobs:
  update-ruleset:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get latest release version
      id: get_release
      run: |
        latest_version=$(curl -s https://api.github.com/repos/MetaCubeX/mihomo/releases/latest | jq -r '.tag_name')
        echo "LATEST_VERSION=${latest_version}" >> $GITHUB_ENV

    - name: Download latest mihomo release
      run: |
        download_url="https://github.com/MetaCubeX/mihomo/releases/download/${{ env.LATEST_VERSION }}/mihomo-linux-amd64-${{ env.LATEST_VERSION }}.deb"
        wget $download_url -O mihomo.deb
        file mihomo.deb
        sudo dpkg -i mihomo.deb

    - name: Download ChinaMax_domain.yaml
      run: |
        wget https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/ChinaMax/ChinaMax_Domain.yaml -O ChinaMax_Domain.yaml
    - name: Download CN-ip-cidr.txt all_cn_ipv6.txt china6.txt
      run: |
        wget https://raw.githubusercontent.com/wendellouyang/geolite2_china_ip_list/main/chnip.txt -O CN-ip-cidr.txt
        wget https://ispip.clang.cn/all_cn_ipv6.txt -O all_cn_ipv6.txt
        wget https://raw.githubusercontent.com/gaoyifan/china-operator-ip/ip-lists/china6.txt -O china6.txt
        cat CN-ip-cidr.txt all_cn_ipv6.txt china6.txt | sort -u > temp_cidrs.txt
        mv temp_cidrs.txt CN-ip-cidr.txt

    - name: Convert txt/yaml to mrs
      run: |
        mihomo convert-ruleset ipcidr text CN-ip-cidr.txt CN-ip-cidr.mrs
        mihomo convert-ruleset domain yaml ChinaMax_Domain.yaml ChinaMax_Domain.mrs

    - name: Remove untracked files
      run: |
        git clean -f all_cn_ipv6.txt china6.txt CN-ip-cidr.txt mihomo.deb ChinaMax_Domain.yaml

    - name: Commit and push mrs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "101653181+github-actions[bot]@users.noreply.github.com"
        git add CN-ip-cidr.mrs ChinaMax_Domain.mrs
        commit_message="Update CN-ip-cidr.mrs on $(date +'%Y-%m-%d')"
        git commit -m "$commit_message" || true
        git push -f -u origin main