name: Update Ruleset

on:
  schedule:
    - cron: '0 6 * * *' # 每天早上6点执行
  push:
    branches:
      - main

jobs:
  update-ruleset:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get latest release version
      id: get_release
      run: |
        latest_version=$(curl -s https://api.github.com/repos/MetaCubeX/mihomo/releases/latest | jq -r '.tag_name')
        echo "LATEST_VERSION=${latest_version}" >> $GITHUB_ENV

    - name: Download latest mihomo release
      run: |
        download_url="https://github.com/MetaCubeX/mihomo/releases/download/${{ env.LATEST_VERSION }}/mihomo-linux-amd64-${{ env.LATEST_VERSION }}.deb"
        wget $download_url -O mihomo.deb
        file mihomo.deb
        sudo dpkg -i mihomo.deb

    - name: Download CN-ip-cidr.txt
      run: |
        wget https://raw.githubusercontent.com/wendellouyang/geolite2_china_ip_list/main/chnip.txt -O CN-ip-cidr.txt

    - name: Convert CN-ip-cidr.txt to CN-ip-cidr.mrs
      run: |
        mihomo convert-ruleset ipcidr text CN-ip-cidr.txt CN-ip-cidr.mrs

    - name: Remove untracked files
      run: |
        git clean -f CN-ip-cidr.txt mihomo.deb

    - name: Commit and push CN-ip-cidr.mrs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "101653181+github-actions[bot]@users.noreply.github.com"
        git add CN-ip-cidr.mrs
        commit_message="Update CN-ip-cidr.mrs on $(date +'%Y-%m-%d')"
        git commit -m "$commit_message"
        git push -f origin main